ENCODED_DATASET_NAME = "cars_encoded.csv"

SEPARATOR = ","

SELECTED_COLS_IN_ENCODED_DATASET = [
    2,
    3,
    15,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    509,
    510,
    511,
    512,
    513,
    514,
    515,
    516,
    517,
    518,
    519,
    520,
    521,
    522,
    523,
    524,
    525,
    526,
    527,
    528,
    529,
    530,
]

ALGORITHM = "simplemargintsm"

SIMPLE_MARGIN_CONFIGURATION = {
    "activeLearner": {
        "name": "SimpleMargin",
        "svmLearner": {
            "C": 1024,
            "kernel": {"gamma": 0, "name": "gaussian"},
            "name": "SVM",
        },
    },
    "subsampleSize": 50000,
    "useFactorizationInformation": False,
}

FACTORIZED_SIMPLE_MARGIN_CONFIGURATION = {
    **SIMPLE_MARGIN_CONFIGURATION,
    "multiTSM": {
        "hasTsm": True,
        "searchUnknownRegionProbability": 0.5,
        "columns": [
            "length",
            "width",
            "price_msrp",
            "class_compact_car",
            "class_compact_crossover_suv",
            "class_compact_mpv",
            "class_compact_suv",
            "class_full_size_car",
            "class_full_size_crossover_suv",
            "class_full_size_pickup_truck",
            "class_full_size_suv",
            "class_full_size_van",
            "class_grand_tourer",
            "class_mid_size_car",
            "class_mid_size_crossover_suv",
            "class_mid_size_pickup_truck",
            "class_mid_size_suv",
            "class_minivan",
            "class_off_road_vehicle",
            "class_roadster_car",
            "class_sport_car",
            "class_sport_cars",
            "class_sport_compact_car",
            "class_subcompact_car",
            "class_subcompact_crossover_suv",
            "class_subcompact_mpv",
            "class_subcompact_suv",
            "class_supercar",
            "fuel_type_diesel_fuel",
            "fuel_type_flex_fuel_premium_unleaded_recommended_e85",
            "fuel_type_flex_fuel_unleaded_e85",
            "fuel_type_flex_fuel_unleaded_natural_gas",
            "fuel_type_premium",
            "fuel_type_premium_unleaded_recommended",
            "fuel_type_premium_unleaded_required",
            "fuel_type_regular_unleaded",
            "transmission_10_speed_shiftable_automatic",
            "transmission_2_speed",
            "transmission_4_speed_automatic",
            "transmission_4_speed_shiftable_automatic",
            "transmission_5_speed_automatic",
            "transmission_5_speed_manual",
            "transmission_5_speed_shiftable_automatic",
            "transmission_6_speed_automated_manual",
            "transmission_6_speed_automatic",
            "transmission_6_speed_manual",
            "transmission_6_speed_shiftable_automatic",
            "transmission_7_speed_automated_manual",
            "transmission_7_speed_automatic",
            "transmission_7_speed_manual",
            "transmission_7_speed_shiftable_automatic",
            "transmission_8_speed_automated_manual",
            "transmission_8_speed_automatic",
            "transmission_8_speed_shiftable_automatic",
            "transmission_9_speed_automated_manual",
            "transmission_9_speed_automatic",
            "transmission_9_speed_shiftable_automatic",
            "transmission_continuously_variable_speed_automatic",
        ],
        "decompose": True,
        "flags": [
            [True, False],
            [True, False],
            [True, True],
            [True, True],
            [True, True],
        ],
        "featureGroups": [
            ["length", "width"],
            ["price_msrp"],
            [
                "class_compact_car",
                "class_compact_crossover_suv",
                "class_compact_mpv",
                "class_compact_suv",
                "class_full_size_car",
                "class_full_size_crossover_suv",
                "class_full_size_pickup_truck",
                "class_full_size_suv",
                "class_full_size_van",
                "class_grand_tourer",
                "class_mid_size_car",
                "class_mid_size_crossover_suv",
                "class_mid_size_pickup_truck",
                "class_mid_size_suv",
                "class_minivan",
                "class_off_road_vehicle",
                "class_roadster_car",
                "class_sport_car",
                "class_sport_cars",
                "class_sport_compact_car",
                "class_subcompact_car",
                "class_subcompact_crossover_suv",
                "class_subcompact_mpv",
                "class_subcompact_suv",
                "class_supercar",
            ],
            [
                "fuel_type_diesel_fuel",
                "fuel_type_flex_fuel_premium_unleaded_recommended_e85",
                "fuel_type_flex_fuel_unleaded_e85",
                "fuel_type_flex_fuel_unleaded_natural_gas",
                "fuel_type_premium",
                "fuel_type_premium_unleaded_recommended",
                "fuel_type_premium_unleaded_required",
                "fuel_type_regular_unleaded",
            ],
            [
                "transmission_10_speed_shiftable_automatic",
                "transmission_2_speed",
                "transmission_4_speed_automatic",
                "transmission_4_speed_shiftable_automatic",
                "transmission_5_speed_automatic",
                "transmission_5_speed_manual",
                "transmission_5_speed_shiftable_automatic",
                "transmission_6_speed_automated_manual",
                "transmission_6_speed_automatic",
                "transmission_6_speed_manual",
                "transmission_6_speed_shiftable_automatic",
                "transmission_7_speed_automated_manual",
                "transmission_7_speed_automatic",
                "transmission_7_speed_manual",
                "transmission_7_speed_shiftable_automatic",
                "transmission_8_speed_automated_manual",
                "transmission_8_speed_automatic",
                "transmission_8_speed_shiftable_automatic",
                "transmission_9_speed_automated_manual",
                "transmission_9_speed_automatic",
                "transmission_9_speed_shiftable_automatic",
                "transmission_continuously_variable_speed_automatic",
            ],
        ],
    },
}

LABELED_POINTS = [
    {"id": 2554, "labels": [1.0, 1.0, 1.0, 1.0, 1.0]},
    {"id": 1064, "labels": [1.0, 0.0, 0.0, 0.0, 1.0]},
]
